site_name: "CS14 SI Labs: Spring 2015"
pages:
    - [index.md, "Home"]
    - [lab_week_01.md, "Lab Week 1"]
    - [lab_week_02.md, "Lab Week 2"]
    - [lab_week_03.md, "Lab Week 3"]
    - [lab_week_04.md, "Lab Week 4"]
    # - [notes.md, "Notes"]
theme: readthedocs

